version: '3.8'

services:
  smartrecipe-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: smartuser
      POSTGRES_PASSWORD: smartpassword
      POSTGRES_DB: smartrecipe
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  smartrecipe-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - smartrecipe-db
    environment:
      - DB_HOST=smartrecipe-db
      - DB_USER=smartuser
      - DB_PASSWORD=smartpassword
      - DB_NAME=smartrecipe
      - DB_PORT=5432
    ports:
      - "4000:4000"
    command: nodemon server.js
    volumes:
      - .:/app

  smartrecipe-frontend:
    image: nginx:latest
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "3000:80"

volumes:
  postgres_data:

