version: '3.8'

services:
  database:
    image: postgres:15
    container_name: smartrecipe-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./smartrecipe.sql:/docker-entrypoint-initdb.d/smartrecipe.sql
      
    ports:
      - "5432:5432"

  frontend:
    container_name: smartrecipe_frontend
    build: frontend
    restart: always
    volumes:
     - frontend_files:/frontend_files
  app:
    build: .
    container_name: smartrecipe-app
    restart: always
    ports:
      - "4000:4000"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      SPOONACULAR_API_KEY: ${SPOONACULAR_API_KEY}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
     - frontend_files:/frontend_files
    depends_on:
      - database
      - frontend

volumes:
  postgres_data:
  frontend_files:
