version: '3.8'

services:
  smartrecipe-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: smartrecipe
      POSTGRES_USER: smartuser
      POSTGRES_PASSWORD: smartpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  smartrecipe-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - smartrecipe-db

  smartrecipe-frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    volumes:
      - frontend_files:/usr/share/nginx/html
    ports:
      - "3000:80"

volumes:
  postgres_data:
  frontend_files:
